[package]
name = "stanco-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }
reqwest = { version = "0.11", features = ["blocking"] }
tar = "0.4"
flate2 = "1.0"

